V22F-479 mouse hovering bug
red-panda-productions/speed-dreams pull request #103
Opened 2022-04-25 12:08 UTC by shoekzema

Fixed hovering over unchecked checkboxes and radiobuttons
Fixed radiobuttons cannot spam click (you needed to remove mouse from button to be able to re-click)
Added hints to text Max-Time and User-ID

2022-04-26 08:09 UTC, suppergerrie2 requested changes
Hovering over the text box for max time doesn't show the hint, but hovering over the text box for user id does.

2022-04-26 08:12 UTC, suppergerrie2 commented
Hovering over the text next to the radio/checkbox buttons doesn't show the hint, it could be nice to do that.

2022-04-27 08:56 UTC, suppergerrie2 approved these changes

2022-04-27 11:16 UTC, larsdekwant approved these changes

2022-04-27 12:36 UTC, merged