Allow FileDataStorage to use local time
red-panda-productions/speed-dreams pull request #104
Opened 2022-04-25 13:44 UTC by Sindarin27

Add a boolean to FileDataStorage on whether to use local or UTC time. Defaults to false, meaning UTC time will be used as before. A function to change this boolean is available for if we decide to add this option in the future.

(very low-priority pull request)

2022-04-26 10:16 UTC, noutheesink approved these changes

2022-04-27 19:52 UTC, sjoeman1 approved these changes

2022-04-27 20:04 UTC, KungFuDonkey approved these changes

2022-04-27 21:09 UTC, KungFuDonkey requested changes
Sorry for the change request after an approve, but the change has not been tested and that needs to be done

2022-04-29 07:36 UTC, closed without merging