V22F-180 replay driver
red-panda-productions/speed-dreams pull request #108
Opened 2022-04-26 14:17 UTC by suppergerrie2

Implement a driver that replays a recording

2022-04-27 09:03 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/drivers/replaydriver/Driver.cpp
> +#define RECORDING_NAME "userRecording20220426-140251"
This is hardcoded for now, will be fixed in another PR

2022-04-27 20:39 UTC, KungFuDonkey approved these changes
The only thing I wonder is the define below, this might be a speed dreams must have, so I won't put it as a change request

2022-04-27 20:40 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/drivers/replaydriver/replaydriver.cpp
> +static const int s_MaxBotAmount = 1;
define?

2022-04-27 21:29 UTC, noutheesink requested changes

2022-04-27 21:29 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/drivers/replaydriver/Driver.cpp
> +/// it opens te replay file and sets the time of the first input
```suggestion
/// it opens the replay file and sets the time of the first input
```

2022-04-27 21:29 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/drivers/replaydriver/Driver.cpp
> +    }
Shouldn't you check for EOF before reading the new input time?
```suggestion
    if (m_replayFile.eof())
    {
        p_situation->raceInfo.state = RM_RACE_ENDED;
    }
    else
    {
        std::string inputTime;
        m_replayFile >> inputTime;
        m_inputTime = std::stod(inputTime);
    }
```

2022-04-28 08:52 UTC, noutheesink approved these changes

2022-04-28 08:56 UTC, merged