V22F-615 Created action for integration tests
red-panda-productions/speed-dreams pull request #116
Opened 2022-04-29 15:25 UTC by KungFuDonkey

This action runs with the OPTION_INTEGRATION_TESTS=ON option, so that in the future this action will run the integration tests.

2022-04-29 15:39 UTC, KungFuDonkey commented
Note: this pr also installs mysql this will also be done in PR #114

2022-04-29 17:01 UTC, suppergerrie2 approved these changes

2022-04-30 10:01 UTC, larsdekwant requested changes

2022-04-30 10:54 UTC, KungFuDonkey commented on .github/workflows/integration-tests.yml
> +        password: PASSWORD
Maybe but this one is only for testing, we could do that with secret keys later

2022-04-30 12:18 UTC, larsdekwant approved these changes

2022-04-30 12:28 UTC, merged