V22F-102 Choosing simulation information
red-panda-productions/speed-dreams pull request #12
Opened 2022-03-15 16:05 UTC by shoekzema

Added a new menu, changed the old menu. Changed the Config (now SDAConfig). Added ConfigTests.

2022-03-15 16:48 UTC, KungFuDonkey requested changes
some p_ are missing from parameters from DataSelectionMenu.cpp Researchmenu.cpp Researchmenu.h

2022-03-17 18:47 UTC, KungFuDonkey commented
Needs to fix merge conflicts with main, you should keep in mind that main has templates now and that the templates should stay

2022-03-17 20:06 UTC, KungFuDonkey requested changes
Research menu should use SMediator to avoid build errors

2022-03-18 09:38 UTC, suppergerrie2 requested changes

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SDAConfig.h
>      InterventionFactory interventionFactory;
```suggestion
    InterventionFactory m_interventionFactory;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
> +typedef unsigned int TASK;
```suggestion
typedef unsigned int Task;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
> +typedef unsigned int INDICATOR;
```suggestion
typedef unsigned int Indicator;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
> +typedef unsigned int PARTICIPANT_CONTROL;
```suggestion
typedef unsigned int ParticipantControl;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
>  typedef unsigned int BLACK_BOX_TYPE;
```suggestion
typedef unsigned int BlackBoxType;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
>  typedef unsigned int DATA_STORAGE_TYPE;
```suggestion
typedef unsigned int DataStorageType;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/ConfigEnums.h
> +typedef unsigned int DATA_TO_STORE;
```suggestion
typedef unsigned int DataToStore;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.h
> +    SDAConfig m_config;
```suggestion
    SDAConfig Config;
```

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/legacymenu.h
>      //! SIMULATED DRIVING ASSISTANCE CHANGE: Activate the intervention menu.
Comment is outdated

2022-03-18 09:38 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/CHANGES.txt
> +        menu/ResearcherMenu.xml
Missing DataSelectionMenu.xml

2022-03-18 15:04 UTC, sjoeman1 requested changes
some coding standards are not adhered, and mediator.h has different indentation

2022-03-18 16:01 UTC, suppergerrie2 approved these changes

2022-03-18 17:31 UTC, sjoeman1 approved these changes

2022-03-19 15:02 UTC, KungFuDonkey approved these changes

2022-03-19 15:03 UTC, merged