V22F-611 Sync blackbox
red-panda-productions/speed-dreams pull request #120
Opened 2022-04-30 19:34 UTC by noutheesink

Blackbox can be run in synchronously. This means the simulation waits for a blackbox decision before it continues. 

PR is still a draf, I'd like it to be reviewed but it still needs to be updated so that the option for sync or async can be chosen

2022-05-01 19:07 UTC, shoekzema requested changes

2022-05-01 19:07 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.inl
>  /// @param p_initialBlackBoxData  The initial drive situation
missing params p_connectAsync, p_tests and p_amountOfTests in documentation

2022-05-01 19:07 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.inl
>  bool SocketBlackBox<BlackBoxData, PointerManager>::GetDecisions(tCarElt* p_car, tSituation* p_situation, unsigned long p_tickCount, DecisionTuple& p_decisions)
missing @param p_decisions in documentation

2022-05-02 07:12 UTC, KungFuDonkey requested changes

2022-05-02 07:12 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SocketBlackBox.inl
> +    std::cout << "sync" << std::endl;
I think we can always do a non-async connection, as doing connectasync() followed by awaitclientconnection is the same as just doing awaitclientconnection

2022-05-02 11:35 UTC, KungFuDonkey approved these changes

2022-05-02 11:56 UTC, shoekzema approved these changes

2022-05-03 07:23 UTC, KungFuDonkey approved these changes

2022-05-03 11:07 UTC, merged