V22F-453 recordings into tests
red-panda-productions/speed-dreams pull request #125
Opened 2022-05-02 12:43 UTC by KungFuDonkey

Implement the recordings into tests so they can be ran and errors can be detected internally in Speed Dreams using an internal driver

2022-05-03 12:41 UTC, noutheesink requested changes

2022-05-03 12:41 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/rppUtils/RppUtils.hpp
> +    LPSTR args = _strdup(p_args);                                   // Create an empty string of arguments for process
The comment on this line is now incorrect

2022-05-06 08:53 UTC, noutheesink approved these changes
It looks like it will work. We should definitely all test it before merging it when everything is finally implemented

2022-05-12 10:02 UTC, larsdekwant requested changes
Clarify test names.

2022-05-12 10:02 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/integrationTests/IntegrationTests.cpp
> +    IntegrationTest,
```suggestion
    TestReplayRecordings,
```

2022-05-12 10:02 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/integrationTests/IntegrationTests.cpp
> +TEST_P(IntegrationTests, IntegrationTest)
```suggestion
TEST_P(IntegrationTests, RunReplayRecording)
```

2022-05-14 11:40 UTC, larsdekwant approved these changes

2022-05-16 09:42 UTC, suppergerrie2 requested changes

2022-05-16 09:42 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/integrationTests/IntegrationTests.cpp
> +    //std::this_thread::sleep_for(std::chrono::seconds(5));
Commented out code should be removed

2022-05-19 10:09 UTC, suppergerrie2 approved these changes

2022-05-19 10:18 UTC, merged