V22F-645 covered car controller
red-panda-productions/speed-dreams pull request #127
Opened 2022-05-02 14:18 UTC by KungFuDonkey

2022-05-02 19:03 UTC, shoekzema requested changes
Missing documentation of CarControllerTests.cpp

2022-05-03 07:23 UTC, shoekzema requested changes

2022-05-03 07:23 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
> +void AccelTest(CarController p_carController, float p_accel)
```suggestion
/// @param p_accel         The acceleration value
void AccelTest(CarController p_carController, float p_accel)
```

2022-05-03 07:23 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
> +void BrakeTest(CarController p_carController, float p_brake)
```suggestion
/// @param p_brake         The brake value
void BrakeTest(CarController p_carController, float p_brake)
```

2022-05-03 07:23 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
> +void ClutchTest(CarController p_carController, float p_clutch)
```suggestion
/// @param p_clutch        The clutch value
void ClutchTest(CarController p_carController, float p_clutch)
```

2022-05-03 07:23 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
> +void LightTest(CarController p_carController, bool p_lights)
```suggestion
/// @param p_lights        The lights value
void LightTest(CarController p_carController, bool p_lights)
```

2022-05-03 07:25 UTC, shoekzema approved these changes

2022-05-03 11:44 UTC, noutheesink requested changes

2022-05-03 11:44 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/CarControllerTests.cpp
> +
I think this should be p_action
```suggestion

    carController.ShowIntervention(p_action);

```

2022-05-03 11:50 UTC, noutheesink approved these changes

2022-05-03 11:57 UTC, merged