Made arrow key controls unable to select labels
red-panda-productions/speed-dreams pull request #130
Opened 2022-05-04 11:10 UTC by shoekzema

It would select labels, but only if the label had a hint.

2022-05-04 14:02 UTC, larsdekwant requested changes

2022-05-04 14:02 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/libs/tgfclient/guiobject.cpp
> +		(curObject->widget != GFUI_LABEL)) {
add this change to CHANGES.txt

2022-05-05 14:19 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/CHANGES.txt
> -                added   GfuiMenuBoolToStr()
whoops

2022-05-05 16:04 UTC, larsdekwant approved these changes

2022-05-06 11:22 UTC, merged