V22F-699 Environment Selection
red-panda-productions/speed-dreams pull request #161
Opened 2022-05-17 14:23 UTC by Sindarin27

Allow selecting environments from the Researcher Menu. Use the selected environment when starting a race.

2022-05-18 12:39 UTC, suppergerrie2 requested changes

2022-05-18 12:39 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/textonly/textonly.cpp
>      auto handle = p_selRaceMan->getDescriptorHandle();
Unused now

2022-05-18 12:39 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/ConfigTests.cpp
> +        path[length - 1] = '\0';
Probably good to use the RandomCharArray function

2022-05-21 08:59 UTC, larsdekwant requested changes
- Evenly spread out controls on the researchermenu (currently there is a large gap between Intervention Type and Participant Control)
- When you go to racestart menu by clicking on Start on the mainmenu, the background is determined by what is selected in the 'Configure' menu of that screen, and not what you selected in the researchermenu. I think the whole Configure button should be removed, since the trackselection that is contained within that menu is completely ignored (but still changes the background of the racestartmenu)

2022-05-23 08:09 UTC, Sindarin27 commented
Removal of Configure button will be done in a separate issue.

2022-05-23 10:04 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/racescreens/raceconfigstate.cpp
> +                ts.piTrackLoader = GfTracks::self()->getTrackLoader();
// SIMULATED DRIVING ASSISTANCE

2022-05-23 10:34 UTC, suppergerrie2 requested changes

2022-05-23 10:34 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/data/data/menu/ResearcherMenu.xml
>          <section name="6">
Shouldn't this be 5 now?

2022-05-23 10:34 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
> +        GfParmSetStr(readParam, PRM_ENVIRONMENT_NAME, GFMNU_ATTR_PATH, m_environment->getId().c_str());
Why not put them in `Environment` category with `category` and `name` as keys:

```xml
  <section name="Environment">
    <attstr name="category" val="road"/>
    <attstr name="name" val="test-highway"/>
  </section>
  ```
  
  VS
  
  ```xml
  

  <section name="EnvironmentCategory">
    <attstr name="path" val="road"/>
  </section>

  <section name="EnvironmentName">
    <attstr name="path" val="test_highway"/>
  </section>
  ```

2022-05-23 12:33 UTC, suppergerrie2 approved these changes

2022-05-23 20:42 UTC, larsdekwant approved these changes

2022-05-24 06:49 UTC, merged