V22F-697 Particpant control: gas, steer and brake
red-panda-productions/speed-dreams pull request #163
Opened 2022-05-18 13:00 UTC by larsdekwant

- Added checkbox for participant control: brake
- Reordered and renamed participant control checkboxes to match the blackbox control checkboxes
- Added functionality to the actual settings so the partipant can only control the specified controls.
- Fixed bug where particpant control on/off setting in controls menu was invisible.

NOTE: nothing changed to the actual steering/throttle/brake functionality, only that it is within an if condition now.

2022-05-18 13:10 UTC, suppergerrie2 requested changes

2022-05-18 13:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/textonly/textonly.cpp
> +    participantControl.ControlSteer = StringToBool(GfParmGetStr(replaySettingsHandle, PATH_PARTICIPANT_CONTROL, KEY_PARTICIPANT_CONTROL_CONTROL_STEERING, "false"));
Missing ControlBrake

2022-05-18 13:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Recorder.cpp
> +    GfParmSetStr(settingsFileHandle, PATH_PARTICIPANT_CONTROL, KEY_PARTICIPANT_CONTROL_CONTROL_STEERING, BoolToString(p_participantControl.ControlSteer));
Missing ControlBrake

2022-05-18 13:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/ConfigTests.cpp
> +    ASSERT_EQ(arr.ControlAccel, pControl.ControlAccel);
Missing ControlBrake

2022-05-18 13:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/MediatorTests.cpp
> +    ASSERT_EQ(arr.ControlAccel, pControl.ControlAccel);
Missing ControlBrake

2022-05-18 13:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/RecorderTests.cpp
> +    participantControl.ControlSteer = random.NextBool();
Missing ControlBrake

2022-05-18 13:48 UTC, sjoeman1 requested changes
The intervention on/off can't use keyboard buttons, could you add that to the hint?
The intervention on/off does not appear to work correctly, also test with abandon race as well as quiting the game

2022-05-18 13:48 UTC, sjoeman1 commented on speed-dreams/source-2.2.3/data/data/menu/controlconfigmenu.xml
>          <attstr name="text" val="MOUSE_MIDDLE_BUTTON"/>
the intervention toggle can't be a key on the keyboard, could you add that to the hint?

2022-05-20 09:41 UTC, suppergerrie2 requested changes
Add changes to Code Changes document

2022-05-20 09:41 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/Recorder.cpp
> +        // If upgrading fails, release handle and exit loop.
This does more than exiting the loop, it returns the entire function

2022-05-20 09:41 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/RecorderTests.cpp
> +/// @brief Tests whether the base-recording is succesfully upgrade to the target version.
```suggestion
/// @brief Tests whether the base-recording is successfully upgrade to the target version.
```

2022-05-20 09:41 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/RecorderTests.cpp
> +INSTANTIATE_TEST_CASE_P(
INSTANTIATE_TEST_CASE_P seems to be deprecated. It says to use INSTANTIATE_TEST_SUITE_P

2022-05-20 20:18 UTC, sjoeman1 approved these changes
The intervention on/off appears to work right now, I did delete my settings folder this time to test it properly, so maybe that had something to do with it

2022-05-21 10:51 UTC, suppergerrie2 approved these changes

2022-05-21 12:19 UTC, merged