V22F-326 Adjust Pause Screen
red-panda-productions/speed-dreams pull request #168
Opened 2022-05-19 13:57 UTC by VoidLeech

Removed quit and force feedback buttons, and renamed the abandon button as stop.
Does not match the Jira task in terms of direct instructions, but the intention of the stop button was covered by the abandon button.

2022-05-19 16:02 UTC, larsdekwant requested changes
Functionality works, but we might have to find a new spot for the 'adjust force feedback' button, since this is the only place where its settings can be adjusted (not talking about just enable/disable, but the actual internal settings)

2022-05-21 09:12 UTC, larsdekwant approved these changes

2022-05-21 11:02 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/data/data/menu/stopracemenu.xml
> +		<attstr name="resume.tip" val="Return to the simulation"/>
Maybe `Return to experiment`?

2022-05-21 11:03 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/data/data/menu/stopracemenu.xml
> +		<attstr name="abort.tip" val="Stop the simulation"/>
Maybe `Stop experiment`?

2022-05-21 11:10 UTC, suppergerrie2 approved these changes

2022-05-21 13:35 UTC, merged