V22 f 675 simple highways
red-panda-productions/speed-dreams pull request #171
Opened 2022-05-20 12:43 UTC by sjoeman1

Added new simple highways with outlines of the tracks.
The tracks are also added to CMake so should be in the installer.
Note: the curved highways are not done yet, but the folders are already created

2022-05-21 09:31 UTC, larsdekwant requested changes
- Give the tracks a clearer name (for the in-game label), currently it says something like 'small 4 lanes 80', but this should be something like 'Highway 4 Lanes [80 km/h]'
- You've added a bunch of empty readme.txt's, is there any reason for this?

2022-05-21 09:31 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/tracks/simple-highway/simple-highway-4-80/simple-highway-4-80.xml
> +    <attstr name="name" val="4 lanes 80" />
This name is actually shown in-game, so should be more clear like:
```suggestion
    <attstr name="name" val="Highway 4 Lanes [80 km/h]" />
```
Or something similar.

2022-05-21 11:17 UTC, suppergerrie2 approved these changes

2022-05-23 14:13 UTC, larsdekwant approved these changes

2022-05-23 16:06 UTC, merged