V22F-666 change order menus
red-panda-productions/speed-dreams pull request #176
Opened 2022-05-21 21:38 UTC by sjoeman1

This PR changes the order of the menus according to the layout we made.
It also makes the cancel and apply buttons consistant on every screen, adds some backgrounds to screens that had missing backgrounds.
It also deletes the raceselectmenu and the racemanmenu and all the menus attached to those

2022-05-22 10:37 UTC, larsdekwant requested changes
According to the diagram the controls menu should be in the options menu, but personally I like the format like this. Either update the diagram (in discussion with the others) or move the menu.

Missing backgrounds:
- save to database menu
- end of experiment menu
- delete data menu

All of the buttons on the menu's above are also slightly too small for the text inside.

2022-05-23 12:44 UTC, suppergerrie2 approved these changes

2022-05-23 14:30 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/racescreens/racenexteventmenu.cpp
> +	GfuiAddKey(rmScrHandle, GFUIK_ESCAPE, "Abandon", rmScrHandle, GfuiScreenActivate, NULL);
// SIMULATED DRIVING ASSISTANCE

2022-05-24 08:39 UTC, larsdekwant requested changes
- Remove the black-box log files from the PR. (the PREFFERED ACTIONS files)
- Fix small code style issues

2022-05-24 08:39 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/optionsmenu.cpp
> +static void onControlMenuActivate(void* /* dummy */)
```suggestion
static void OnControlMenuActivate(void* /* dummy */)
```

2022-05-24 08:39 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/racescreens/racenexteventmenu.cpp
> +	GfuiMenuCreateButtonControl(rmScrHandle, menuXMLDescHdle, "AbandonButton", rmScrHandle, GfuiScreenActivate);
remove tab

2022-05-24 14:02 UTC, larsdekwant approved these changes

2022-05-25 09:30 UTC, merged