V22F-795 Add new intervention type
red-panda-productions/speed-dreams pull request #185
Opened 2022-05-28 14:13 UTC by klieverse

2022-05-30 08:29 UTC, suppergerrie2 requested changes

2022-05-30 08:29 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/libs/robottools/rthumandriver.cpp
> +    }
This is getting a lot, maybe this can become a method in the mediator? SMediator::CanUserSteer()?
Same for brake and accel.

2022-05-31 17:19 UTC, suppergerrie2 requested changes

2022-06-01 09:22 UTC, noutheesink requested changes

2022-06-01 14:02 UTC, noutheesink requested changes

2022-06-01 14:02 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/MediatorTests.cpp
> +    for (int i = 0; i < 2 * TEST_AMOUNT; i++)
Rather not just do these tests twice as much to get all combinations covered. Pairwise tests or something would be better

2022-06-02 09:24 UTC, noutheesink approved these changes

2022-06-02 09:34 UTC, merged