V22F-873 Updated the EndExperimentMenu button and relocated it
red-panda-productions/speed-dreams pull request #202
Opened 2022-06-02 19:59 UTC by Meaganium

2022-06-02 20:22 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/EndExperimentMenu.xml
> +		</section>
I think you might still have tabs as default in your IDE, replace tabs with spaces.

2022-06-03 06:34 UTC, larsdekwant requested changes

2022-06-03 06:34 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/EndExperimentMenu.xml
> +            <attstr name="tip" val="Exit from the experiment"/>
Update this to something like 'Continue to the save data screen'

2022-06-03 06:34 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/EndExperimentMenu.xml
> +            <attstr name="font" val="medium"/>
I would keep the font size big, since it's a single button on the screen

2022-06-03 08:02 UTC, suppergerrie2 approved these changes

2022-06-03 13:10 UTC, larsdekwant approved these changes

2022-06-03 13:18 UTC, merged