V22F-888 data is not saved when max time runs out
red-panda-productions/speed-dreams pull request #210
Opened 2022-06-08 08:18 UTC by MaikVink

create functions for it, like requested in the Jira task.

2022-06-08 10:45 UTC, noutheesink requested changes

2022-06-08 12:05 UTC, MaikVink commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/racescreens/racestopmenu.cpp
> +        GfuiScreenActivate(ExitMenuInit(rmStopScrHandle, true, /*RACE_EXIT*/ -1));
As the person who changed this I can safely say that it can be removed now

2022-06-08 12:06 UTC, MaikVink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
>  }
I have changed it so that the blackbox.shutdown immediatly happens after saving the data. You should take a look if this is what you require.

2022-06-08 14:32 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
>  }
The blackbox doesn´t shutdown anymore if you decide not to save

2022-06-09 08:12 UTC, MaikVink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
>  }
moved it to a seperate function and changed some other parts

2022-06-09 16:17 UTC, KungFuDonkey approved these changes

2022-06-09 16:29 UTC, merged