V22F-810 Check database user's privileges
red-panda-productions/speed-dreams pull request #220
Opened 2022-06-13 14:42 UTC by Sindarin27

- Add method TestConnection to test connection to database in SQLDatabaseStorage
- Split methods CreateDatabaseSchema and ConnectDatabase from OpenDatabase
- Add method GetMissingPrivileges to get list of missing privileges
- Expand error log message in DatabaseConnectionManager.cpp
- Use TestConnection instead of OpenDatabase in Mediator's CheckConnection
- Make PutKeys public static to make it reusable
- Add tests for TestConnection function

2022-06-13 15:08 UTC, noutheesink requested changes

2022-06-13 15:08 UTC, noutheesink commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SQLDatabaseStorageTests.cpp
> +        "SQL connection test failed: Database user " TEST_UNPRIVILEGED_USER_USERNAME " is missing ");
The error that is caught sounds like an error about the user not existing, but the comment says it's about checking permissions? Am I not seeing something or is this wrong?

2022-06-14 07:35 UTC, Sindarin27 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SQLDatabaseStorageTests.cpp
> +    statement->execute("CREATE USER IF NOT EXISTS '" TEST_UNPRIVILEGED_USER_USERNAME "'@'localhost' IDENTIFIED by '" TEST_UNPRIVILEGED_USER_PASSWORD "'");
Yes. This way the user is only created on the localhost and not accessible by any other devices.

2022-06-15 05:48 UTC, KungFuDonkey approved these changes

2022-06-15 10:02 UTC, merged