Researcher menu
red-panda-productions/speed-dreams pull request #26
Opened 2022-03-20 16:29 UTC by shoekzema

Filled in the empty researchermenu with checkboxes and text input field that work with the config.

2022-03-20 19:11 UTC, suppergerrie2 requested changes

2022-03-20 19:11 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/data/Singletons/Mediator
> +09F1A668
This should not be pushed

2022-03-20 19:11 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
> +}
This makes it so you can have task lane keeping selected in the menu but the program thinks nothing is selected, to reproduce: Select both, then deselect speed control

2022-03-20 19:11 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
> +    GfuiMenuCreateCheckboxControl(s_scrHandle, param, "CheckboxType4", NULL, SelectTypeCompleteTakeover);
CheckboxType1 is quite a generic name, maybe something more specific like CheckboxTypeNoSignals would be better

2022-03-20 20:32 UTC, shoekzema commented
The hoverability of SD menu parts are very janky, so text input fields have them, but they don't work and checkboxes only work if they are checked.

2022-03-21 07:55 UTC, suppergerrie2 requested changes

2022-03-21 07:55 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
> +    else if (m_task = TASK_LANE_KEEPING)
This will always return true since you use a single `=`

2022-03-22 08:45 UTC, suppergerrie2 approved these changes

2022-03-22 08:46 UTC, merged