V22F-268 Added back-buttons
red-panda-productions/speed-dreams pull request #41
Opened 2022-03-25 14:54 UTC by shoekzema

Also made some small refactors and relocated variable initialization from OnActivate() to MenuInit(), this way it remembers what was selected.

2022-03-28 09:07 UTC, larsdekwant requested changes

2022-03-28 09:07 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DataSelectionMenu.cpp
> +/// @brief Activates the researchMenu screen
```suggestion
/// @brief Returns to the researcher menu screen
```

2022-03-30 08:26 UTC, suppergerrie2 requested changes
When in the second menu (Data selection) and pressing escape the game crashes

2022-03-30 11:09 UTC, suppergerrie2 approved these changes

2022-03-30 11:46 UTC, larsdekwant approved these changes

2022-03-30 13:38 UTC, merged