V22F-306 Add working force feedback option
red-panda-productions/speed-dreams pull request #48
Opened 2022-04-01 10:30 UTC by shoekzema

Tested by looking at the forcefeedback checkbox in pause while racing.

2022-04-01 12:03 UTC, larsdekwant approved these changes
Only seems to work when first starting the game, but not when abandoning a race and then changing the force feedback. This might however be something that needs to be fixed with the entire menu (settings not correctly applying when changed)

2022-04-01 13:20 UTC, KungFuDonkey approved these changes

2022-04-02 13:27 UTC, suppergerrie2 requested changes
Only works when you first start the game, look into how speed dreams saves and loads the forcefeedback since the behaviour seems to differ after you start a race (carName is different)

2022-04-02 13:55 UTC, suppergerrie2 approved these changes

2022-04-02 13:55 UTC, shoekzema commented
It does work, the checkboxes in the menu while racing just don't update. Only sets the checks in the checkboxes the first time

2022-04-02 13:57 UTC, merged