V22F-168 Remove unused HUD elements
red-panda-productions/speed-dreams pull request #49
Opened 2022-04-01 11:02 UTC by larsdekwant

Removed all hud elements and function references that will be completely unnecessary for the intervention HUD. 
This only leaves the speed and gear instruments, debug info (fps, etc) and the interventions themselves.

2022-04-01 11:38 UTC, KungFuDonkey approved these changes

2022-04-02 13:54 UTC, suppergerrie2 requested changes

2022-04-02 13:54 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.cpp
> +// SIMULATED DRIVING ASSISTANCE: removed functions of unused hud elements (see sda/CHANGES.TXT)
sda/CHANGES.txt should preferably be the entire path and not use abbreviations

2022-04-04 08:18 UTC, suppergerrie2 approved these changes

2022-04-04 08:23 UTC, merged