V22 f 293 update ipc lib
red-panda-productions/speed-dreams pull request #50
Opened 2022-04-01 12:58 UTC by KungFuDonkey

Updates the ipc lib to use initialization methods

2022-04-02 15:11 UTC, shoekzema requested changes

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_FALSE(bb.GetDecisions(&car,&situation,0, decisions));
```suggestion
	ASSERT_FALSE(bb.GetDecisions(&car, &situation, 0, decisions));
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()), IPCLIB_SUCCEED);
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()), IPCLIB_SUCCEED);
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()), IPCLIB_SUCCEED);
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()), IPCLIB_SUCCEED);
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData(sbuffer.data(), sbuffer.size()), IPCLIB_SUCCEED);
```

2022-04-02 15:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SocketBlackBoxTests.h
> +	ASSERT_EQ(client.SendData("OK", 2),IPCLIB_SUCCEED);
```suggestion
	ASSERT_EQ(client.SendData("OK", 2), IPCLIB_SUCCEED);
```

2022-04-04 08:17 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/BlackBoxData.cpp
> +BlackBoxData::BlackBoxData(tCarElt* p_car, tSituation* p_situation, int p_tickCount)
will be done in the other branch

2022-04-04 09:20 UTC, shoekzema approved these changes

2022-04-04 10:34 UTC, noutheesink approved these changes

2022-04-04 10:35 UTC, merged