V22F-367 Researcher menu text checkbox
red-panda-productions/speed-dreams pull request #52
Opened 2022-04-01 13:10 UTC by larsdekwant

Added a Text checkbox to the Researchermenu and made sure to actually use these settings while drawing the HUD.
Note that currently the Visual checkbox is more important than the Textual checkbox, since Text is already a Visual indicator.

2022-04-01 13:19 UTC, KungFuDonkey approved these changes
Look good!

2022-04-02 14:11 UTC, shoekzema requested changes

2022-04-02 14:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.cpp
> +  // Draw the intervention only when enabled in the settings
```suggestion
  // SIMULATED DRIVING ASSISTANCE:
  // Draw the intervention only when enabled in the settings
```

2022-04-02 14:11 UTC, shoekzema commented on speed-dreams/source-2.2.3/src/modules/graphic/ssggraph/grboard.cpp
> +#include "Mediator.h"
add to the CHANGES.txt:
included "Mediator.h"

2022-04-02 14:22 UTC, suppergerrie2 approved these changes

2022-04-04 08:35 UTC, shoekzema approved these changes

2022-04-04 08:36 UTC, merged