V22F-304 Linting
red-panda-productions/speed-dreams pull request #80
Opened 2022-04-15 11:24 UTC by KungFuDonkey

2022-04-15 16:54 UTC, KungFuDonkey commented
![image](https://user-images.githubusercontent.com/43845930/163598568-c9ea24d4-8e3c-4ac3-b1f8-edee1ba2cf5f.png)

2022-04-18 15:55 UTC, suppergerrie2 requested changes

2022-04-18 15:55 UTC, suppergerrie2 commented on .github/workflows/linting.yml
> +        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DOPTION_PACKAGING=0 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER
```suggestion
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DOPTION_PACKAGING=0 -S '${{github.workspace}}/speed-dreams/source-2.2.3' -B '${{runner.workspace}}/build' -G Ninja
```

2022-04-18 18:35 UTC, suppergerrie2 requested changes

2022-04-18 18:35 UTC, suppergerrie2 commented on .github/workflows/linting.yml
> +        # run: exit 1
```suggestion
```

2022-04-18 18:35 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/LinterTests/CMakeLists.txt
> +
Is this folder/file still needed?

2022-04-18 18:49 UTC, suppergerrie2 approved these changes

2022-04-18 18:59 UTC, larsdekwant approved these changes

2022-04-18 18:59 UTC, merged