moved build and find logs of speed dreams to an option
red-panda-productions/speed-dreams pull request #87
Opened 2022-04-18 19:33 UTC by KungFuDonkey

2022-04-18 19:36 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/cmake/FindMYSQL.cmake
> -MESSAGE(STATUS "${MYSQL_INCLUDE_DIR}")
These were made by me, I forgot to remove them

2022-04-18 19:36 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/cmake/checks.cmake
> -#		IF(MYSQL_CPPCONN_STATIC_LIBRARY)
Made by me, also forgot to remove them

2022-04-18 19:56 UTC, larsdekwant approved these changes

2022-04-19 13:34 UTC, suppergerrie2 requested changes
It defaults to OFF

2022-04-19 13:34 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/CMakeLists.txt
> +OPTION(OPTION_SD_CMAKE_FIND_LOGS TRUE)
I think you should use ON since it seems to default to OFF for me

2022-04-19 16:40 UTC, suppergerrie2 approved these changes

2022-04-19 17:12 UTC, merged