V22F-374 Fix arrow key wrong order
red-panda-productions/speed-dreams pull request #90
Opened 2022-04-19 11:01 UTC by shoekzema

Also added arrow key control functionality to ResearcherMenu and DataSelectionMenu.

2022-04-19 18:02 UTC, suppergerrie2 approved these changes

2022-04-20 14:52 UTC, larsdekwant requested changes
Implement the requested changes by the linter as well

2022-04-20 14:52 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/ResearcherMenu.cpp
> +    if (m_maxTime > 1440)
Make 1440 a defined constant instead of a magic number.

2022-04-20 17:42 UTC, shoekzema commented
I won't solve the rest of the clang-tidy things as they are about things in Speed Dreams

2022-04-21 09:24 UTC, larsdekwant approved these changes

2022-04-21 10:39 UTC, merged