V22F-518 File path database storage
red-panda-productions/speed-dreams pull request #95
Opened 2022-04-21 18:23 UTC by noutheesink

The path given to the database storage was not the same path as the buffer file. Fixed now

2022-04-21 19:38 UTC, KungFuDonkey requested changes
Please merge with main to remove commits from the other PR

2022-04-22 10:28 UTC, Sindarin27 requested changes

2022-04-22 10:28 UTC, Sindarin27 commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/DecisionMaker.inl
> +        BUFFER_FILE_PATH,
The value of BUFFER_FILE_PATH should also be updated now that the temporary directory is properly used

2022-04-22 10:57 UTC, Sindarin27 approved these changes

2022-04-22 11:00 UTC, KungFuDonkey requested changes

2022-04-22 11:00 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.cpp
> +void FileDataStorage::SaveDecisions(DecisionTuple &p_decisions)
should be on left side

2022-04-22 11:00 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.cpp
> +void FileDataStorage::Save(tCarElt *p_car, tSituation *p_situation, unsigned long p_timestamp)
should be on left side

2022-04-22 11:00 UTC, KungFuDonkey commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/FileDataStorage.cpp
> +    const std::string &p_fileName,
should be on left side

2022-04-22 14:20 UTC, KungFuDonkey approved these changes

2022-04-22 17:03 UTC, merged